FROM golang:1.23-alpine
WORKDIR /app

RUN apk --no-cache add ca-certificates && \
    go install github.com/air-verse/air@v1.52.3

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
